# Generated by Django 4.2.20 on 2025-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('sn_resp', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
    ]
