# Generated by Django 4.2.20 on 2025-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_alter_ambiente_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='sig',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
