# Generated by Django 4.2.20 on 2025-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutentores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutentor',
            name='sn_manu',
            field=models.CharField(max_length=20),
        ),
    ]
